# Build native lib
name: Build Rust Native Libraries

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            out_dir: linux-x86-64
            lib_pattern: "lib*.so"

          - os: windows-latest
            out_dir: windows-x86-64
            lib_pattern: "*.dll"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Build Rust library
        working-directory: rust-core
        run: cargo build --release --lib

      - name: Prepare output directory
        shell: bash
        run: |
          mkdir -p resources/${{ matrix.out_dir }}

      - name: Copy native library
        shell: bash
        run: |
          FILE=$(find rust-core/target/release -maxdepth 1 -type f -name "${{ matrix.lib_pattern }}" | head -n 1)

          if [ -z "$FILE" ]; then
            echo "Native library not found!"
            exit 1
          fi

          cp "$FILE" resources/${{ matrix.out_dir }}/

      - name: Show output
        shell: bash
        run: |
          ls -R resources

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: native-libs-${{ matrix.out_dir }}
          path: resources/${{ matrix.out_dir }}